### ISSUE TITLE
you're bad

### ISSUE THREAD

**Issue by xFreshie** [voidedWarranties/voidmern#1]
DID SOMEBODY SAY WEBSITE
DID SOMEBODY SAY WEBSITE
DID SOMEBODY SAY WEBSITE
DID SOMEBODY SAY WEBSITE
DID SOMEBODY SAY WEBSITE
DID SOMEBODY SAY WEBSITEDID SOMEBODY SAY WEBSITE
DID SOMEBODY SAY WEBSITE
DID SOMEBODY SAY WEBSITE
DID SOMEBODY SAY WEBSITE
DID SOMEBODY SAY WEBSITE
DID SOMEBODY SAY WEBSITE

**Comment by voidedWarranties** [comment]
Unacceptable as an issue. Fresh, I'm very disappointed in you. Also,


DID SOMEBODY SAY WEBSITE
